### ISSUE TITLE
Update for 3.1

### ISSUE THREAD

**Issue by keith-hall** [maliayas/SublimeText_Documentation#2]
Hi,

Sublime Text 3.1 was released today, please can you update this repo with the latest docs changes.

Also, the tagline for this repo is:

> Daily unofficial mirror of the ST 3 documentation

does that mean that you have an automated process set up to update this repo? In which case probably my issue here is redundant, but from what I've seen it's not picked up changes at all recently...

Thanks :)

**Comment by maliayas** [comment]
Hi guys,

I wasn't watching this repo actively. Sorry for not noticing this issue on time. I've just pushed the new stuff, so you can check it now.

The process is half-automatic. It works from my home PC. When something new is found, it makes a local commit and notifies me. Then I check the commit to see if it has noises (sometimes it has unrelated noisy diffs). If the diff is OK, I manually push the repo.

So that's how it works. Cheers!
